-- StudentHub V14: Ratings & Reviews
-- Run this once in Supabase SQL Editor.
create table if not exists public.studenthub_reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null default 'Student',
  rating integer not null check (rating between 1 and 5),
  review_text text not null default '' check (char_length(review_text) <= 500),
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.studenthub_reviews enable row level security;

drop policy if exists "Public can read approved reviews" on public.studenthub_reviews;
create policy "Public can read approved reviews"
on public.studenthub_reviews for select
using (approved = true);

drop policy if exists "Users can submit own reviews" on public.studenthub_reviews;
create policy "Users can submit own reviews"
on public.studenthub_reviews for insert
to authenticated
with check (auth.uid() = user_id and approved = false);

-- Users cannot publish/approve their own review. Approval can be done later by an admin/service role.
